name: Build and push image

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-push:
    name: "Build and push"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=${SHA}" >> $GITHUB_OUTPUT

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v2

      # - name: Build tagged docker image
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
      #     IMAGE_TAG: ${{ steps.generate_sha.outputs.sha }}
      #   run: docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

       - name: Build tagged docker image
        env:

          IMAGE_TAG: ${{ steps.generate_sha.outputs.sha }}
        run: docker build -t tools-control-frontend:$IMAGE_TAG .

      # - name: Push image to Amazon ECR
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
      #     IMAGE_TAG: ${{ steps.generate_sha.outputs.sha }}
      #   run: |
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
